project_id = "dugdcacjxebgtsdafeel"

[functions.analyze-problem]
verify_jwt = false

[functions.check-syntax]
verify_jwt = false

[functions.generate-test-cases]
verify_jwt = false

[functions.execute-code]
verify_jwt = false

[functions.diagnose-bug]
verify_jwt = false

[functions.debug-chat]
verify_jwt = false

[functions.wrap-class-code]
verify_jwt = false
